name: Deploy to Lambda and Redeploy APIs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (if needed)
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      - name: Install zip
        run: sudo apt-get install zip

      - name: Create lambda.zip
        run: |
          cd backend
          zip -r lambda.zip . -x ".env" ".gitignore"

      - name: Upload to AWS Lambda
        uses: aws-actions/aws-cli-action@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update Lambda function code
        run: |
          cd backend
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://lambda.zip

      - name: Redeploy all APIs
        run: |
          echo "Redeploying APIs..."
          aws apigateway create-deployment \
            --rest-api-id ${{ secrets.API_ID }} \
            --stage-name ${{ secrets.API_STAGE }} \
            --description "Redeploy API after Lambda update"
